### ISSUE TITLE
Missing Version Key in Manifest file which will create an issue in later versions.

### ISSUE THREAD

**Issue by johanschelin** [And3rsL/Deebot-for-Hassio#100] opened 2021-04-12 08:57 UTC
This error is logged in my Home Assistant v 2021.3.4 with Deebot 2.0.1

2021-04-12 10:53:42 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'deebot'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'deebot'

**Comment by edenhaus** [comment] 2021-04-15 19:21
Duplicate of #80

**Closed by edenhaus** 2021-04-15 19:21 UTC
Labels: bug
