### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'deebot'

### ISSUE THREAD

**Issue by ippo1000** [And3rsL/Deebot-for-Hassio#102] opened 2021-04-16 12:17 UTC
Good Morning, i have this issue how i can solve? 

No 'version' key in the manifest file for custom integration 'deebot'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'deebot'

Thanks

**Comment by elahd** [comment] 2021-04-22 21:49
This is a dupe of #80.

**Closed** 2021-04-26 14:40 UTC
Labels: bug
