### ISSUE TITLE
Home Assistant slow startup due to Deboot for Hassio integration

### ISSUE THREAD

**Issue by SmartM-ui** [And3rsL/Deebot-for-Hassio#114] opened 2021-05-07 10:45 UTC
Hi,
after updating the integration, Home Assistant starts up particularly slow. 
The integration takes approximately 45 seconds to start.
Before the integration update, the Home Assistant restart was not slowed and the integration took less than 10 seconds to start in the background, without affecting the HA startup time.

**Comment by edenhaus** [comment] 2021-05-10 21:06
Duplicate of #113

**Closed by edenhaus** 2021-05-10 21:06 UTC
