### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'deebot'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'deebot'

### ISSUE THREAD

**Issue by LuckyTriple7** [And3rsL/Deebot-for-hassio#88] opened 2021-03-04 06:49 UTC
https://developers.home-assistant.io/docs/creating_integration_manifest

**Comment by skynetua** [comment] 2021-03-04 09:34
Duplicate of #80

**Closed** 2021-03-04 13:37 UTC
Labels: bug
